Emit sudt transfer log
nervosnetwork/godwoken-scripts pull request #10
Opened 2021-03-26 05:07 UTC by TheWaWaR

2021-04-09 09:52 UTC, jjyr requested changes

2021-04-09 09:52 UTC, jjyr commented on c/sudt_utils.h
> +  data[1] = SUDT_OPERATION_TRANSFER;
```suggestion
  data[0] = SUDT_OPERATION_TRANSFER;
```

2021-04-09 09:52 UTC, jjyr commented on c/sudt_utils.h
> +#define SUDT_OPERATION_TRANSFER 0x00
```suggestion
#define SUDT_OPERATION_TRANSFER 0x0
```

2021-04-12 06:51 UTC, TheWaWaR commented on c/sudt_utils.h
> +  data[1] = SUDT_OPERATION_TRANSFER;
Interesting, let me see how tests passed ...

2021-04-12 08:04 UTC, jjyr approved these changes

2021-04-12 08:04 UTC, merged