feat: add overwrite param when update eth addr reg
nervosnetwork/godwoken-scripts pull request #119
Opened 2022-05-09 03:28 UTC by magicalne

Add `overwrite` param when updating mapping between eth addr and script hash. So that we can choose to overwrite mapping or not if there is an address collision.

2022-05-09 10:11 UTC, Flouse approved these changes

2022-05-10 02:56 UTC, Flouse requested changes
When `overwrite == true`, I think we should delete the old mapping data.

2022-05-10 07:56 UTC, magicalne commented
> When `overwrite == true`, I think we should delete the old mapping data.

Done.

2022-05-11 02:47 UTC, jjyr approved these changes

2022-05-11 02:59 UTC, jjyr commented
We can clear the existed mapping record when overwrite is true, thus, we do not need to add a new method. I have pushed a commit to do this please review @magicalne

2022-05-11 03:05 UTC, Flouse approved these changes

2022-05-11 03:52 UTC, zeroqn approved these changes

2022-05-11 04:30 UTC, merged