feat: replace with ckb merkle proof and fix tests
nervosnetwork/godwoken-scripts pull request #79
Opened 2021-08-31 02:07 UTC by magicalne

failures:
    script_tests::state_validator::cancel_challenge::test_burn_challenge_capacity
    script_tests::state_validator::cancel_challenge::tx_execution::test_cancel_tx_execute
    script_tests::state_validator::cancel_challenge::tx_signature::test_cancel_tx_signature
    script_tests::state_validator::cancel_challenge::withdrawal::test_cancel_withdrawal
    script_tests::state_validator::enter_challenge::test_enter_challenge
    script_tests::state_validator::enter_challenge::test_enter_challenge_finalized_block
    script_tests::state_validator::revert::test_revert

test result: FAILED. 18 passed; 7 failed; 0 ignored; 0 measured; 0 filtered out; finished in 3.37s

error: **DB error unexpected prev tx state', tests/src/testing_tool/chain.rs:190:23**

2021-09-01 15:45 UTC, jjyr commented
Can you upgrade this PR?

2021-09-02 01:28 UTC, magicalne commented
I will push the updates. But tests haven't been fixed yet.

2021-09-06 11:33 UTC, jjyr commented
Is this PR ready for merge? can we change the status to `ready for review`?

2021-09-06 11:55 UTC, magicalne commented
Sure. Just need to update cargo dependency after https://github.com/nervosnetwork/godwoken/pull/318 is merged.

2021-09-07 08:50 UTC, jjyr requested changes

2021-09-07 08:50 UTC, jjyr commented on tests/src/script_tests/state_validator/cancel_challenge/tx_execution.rs
> -        .allowed_eoa_type_hashes(PackVec::pack(allowed_eoa_type_hashes))
We should use eoa_lock_type_hash and remove `ALWAYS_SUCCESS_CODE_HASH`.

2021-09-07 08:50 UTC, jjyr commented on tests/src/script_tests/state_validator/cancel_challenge/withdrawal.rs
> +    account_lock_manage.register_lock_algorithm(eoa_lock_type_hash.into(), Box::new(AlwaysSuccess));
Duplicated

2021-09-11 15:51 UTC, merged